name: datamanager
description: Rust Flutter Study
publish_to: "none"
version: 1.0.0

environment:
  sdk: "2.17.5"
  flutter: "3.0.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: "1.0.5"
  flutter_bloc: "8.0.1"
  intl: "0.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "2.0.1"

flutter:
  uses-material-design: true
  generate: true